pool:
  vmimage: windows-latest

trigger:
- master

variables:
  BuildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 1.1.x'
  inputs:
    version: 1.1.x

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 2.x'
  inputs:
    version: 2.x

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.0.x'
  inputs:
    version: 3.0.x

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.1.x'
  inputs:
    version: 3.1.x

- checkout: git://Microsoft.Extensions.Logging.Log4Net.AspNetCore/Log4Net.Cert

- bash: |
    cd Log4Net.Cert
    cp Microsoft.Extensions.Logging.Log4Net.AspNetCoreKey.snk $BUILD_SOURCESDIRECTORY/src/Microsoft.Extensions.Logging.Log4Net.AspNetCore
  displayName: 'Bash Script'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '$(Build.SourcesDirectory)/**/*csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: |
     $(Build.SourcesDirectory)/**/*csproj
     !$(Build.SourcesDirectory)/**/NetFrameworkv4_7_2/*.csproj
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: |
     $(Build.SourcesDirectory)/**/*.csproj
     !$(Build.SourcesDirectory)/**/NetFramework.v472.Tests/*.csproj
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: '$(Build.SourcesDirectory)/**/Microsoft.Extensions.Logging.Log4Net.AspNetCore.csproj'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: nuget'
  inputs:
    ArtifactName: nuget


