name: 👀 Pull Request Checks
on:
  workflow_dispatch:
    pull_request:
      types: [opened, edited, synchronize]

env:
  SOLUTION_PATH: ./src/Microsoft.Extensions.Logging.Log4net.sln
  SNK_PATH: src/Microsoft.Extensions.Logging.Log4Net.AspNetCore/Microsoft.Extensions.Logging.Log4Net.AspNetCoreKey.snk

jobs:
  build:
    name: 🚀🧪 Check PR
    runs-on: windows-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: 🔐 Materialize Signing Key
        run: |
          $signing_keys_payload = [System.Convert]::FromBase64String("${{ secrets.SIGNING_KEY }}")
          $currentDirectory = Get-Location
          $certificatePath = Join-Path -Path $currentDirectory -ChildPath "{{ env.SNK_PATH }}"
          [IO.File]::WriteAllBytes("$certificatePath", $signing_keys_payload)

      - name: 🏗 Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
            5.0.x
            3.1.x

      - name: 🛠 Restore packages
        run: dotnet restore "${{ env.SOLUTION_PATH }}"

      - name: 🧪 Test
        run: dotnet test "${{ env.SOLUTION_PATH }}"
